var cinema = [{
    "Title": "Being Julia",
    "fulltitle": "Being Julia (2004)",
    "movie_year": 2004,
    "Categories": "Comedy|Drama|Romance",
    "summary": "1938. Julia Lambert and Michael Gosselyn are the royal couple of the London theater scene, Julia an actress and Michael a former actor who took over running the theater and its troupe upon the passing of their mentor, Jimmie Langton. Jimmie is still constantly with Julia in spirit as she navigates through life. Besides their work, Julia and Michael lead largely separate lives, they long ago having stopped a sexual relationship. Julia of late has been feeling disenchanted with her life, she not wanting to admit it's because she is approaching middle age. Her disenchantment manifests itself in wanting Michael to close their current production early so that she can recharge her juices, something he is reluctant to do if only for not wanting to let the theater sit empty. What Julia ends up doing instead is embarking on an affair with Tom Fennel, an adoring young American who is young enough to be her son. As Julia and Tom's relationship progresses, the more she falls in love with him and ...",
    "ImageURL": "https://hydramovies.com/wp-content/uploads/2018/04/Being-Julia-Movie-Poster.jpg",
    "imdb_id": "tt0340012",
    "imdb_rating": 7,
    "runtime": 104,
    "language": "English",
    "ytid": "quzIsJq7t08"
  },
  {
    "Title": "Trouble Is My Business",
    "fulltitle": "Trouble Is My Business (2018)",
    "movie_year": 2018,
    "Categories": "Action|Adventure|Crime|Mystery|Thriller",
    "summary": "Los Angeles in 1947, everything should be sunny, but the smog creates a fog, a haze that permeates not just the lungs, but the psyches. Private eye Roland Drake cracks cases and romances femme fatales, while corrupt cops rule the underworld of the city and moral lines are anything but black and white. A dark, hard-boiled tale of love and betrayal, told in the classic style of film noir. Drake has fallen on hard times in a harsh world. He has been evicted from his office and disgraced by a missing persons case. Ruined in the public eye and with the police. it seems like it's all over for Roland Drake. Then, redemption walks in - with curves. The owner of those curves is a sexy, dark haired beauty named Katherine Montemar. She wants his help. The chemistry is immediate and her concern for the disappearance of her family members pulls him into her case - and into bed. He wakes up to her missing too, and a pool of blood where she used to be. After a nervous encounter with the equally ...",
    "ImageURL": "https://hydramovies.com/wp-content/uploads/2018/04/Trouble-Is-My-Business-Movie-Poster.jpg",
    "imdb_id": "tt2243900",
    "imdb_rating": 6.1,
    "runtime": 116,
    "language": "English",
    "ytid": "SqUEOsQf6hM"
  },
  {
    "Title": "Outside In",
    "fulltitle": "Outside In (2017)",
    "movie_year": 2017,
    "Categories": "Drama",
    "summary": "An ex-con struggling to readjust to life in his small town forms an intense bond with his former high school teacher.",
    "ImageURL": "https://hydramovies.com/wp-content/uploads/2018/04/Outside-In-Movie-Poster.jpg",
    "imdb_id": "tt7260048",
    "imdb_rating": 6.4,
    "runtime": 109,
    "language": "English",
    "ytid": "s0SdJfplC80"
  },
  {
    "Title": "Froning: The Fittest Man in History",
    "fulltitle": "Froning: The Fittest Man in History (2015)",
    "movie_year": 2015,
    "Categories": "Documentary",
    "summary": "Rich Froning Jr. is a legend in CrossFit and the Sport of Fitness. In this biopic, take a look at his childhood, follow his quest for a fourth CrossFit Games title, and see him as a son, a husband and a new father.",
    "ImageURL": "https://hydramovies.com/wp-content/uploads/2018/04/Froning-The-Fittest-Man-in-History-Movie-Poster.jpg",
    "imdb_id": "tt5079382",
    "imdb_rating": 6.7,
    "runtime": 99,
    "language": "English",
    "ytid": "D1ze-f7jS2A"
  },
  {
    "Title": "Elizabethtown",
    "fulltitle": "Elizabethtown (2005)",
    "movie_year": 2005,
    "Categories": "Comedy|Drama|Romance",
    "summary": "After causing a loss of almost one billion dollars in his company, the shoe designer Drew Baylor decides to commit suicide. However, in the exact moment of his act of despair, he receives a phone call from his sister telling him that his beloved father had just died in Elizabethtown, and he should bring him back since his mother had problem with the relatives of his father. He travels in an empty red eye flight and meets the attendant Claire Colburn, who changes his view and perspective of life.",
    "ImageURL": "https://hydramovies.com/wp-content/uploads/2018/04/Elizabethtown-Movie-Poster.jpg",
    "imdb_id": "tt0368709",
    "imdb_rating": 6.4,
    "runtime": 123,
    "language": "English",
    "ytid": "qyPq2BS8Ug0"
  },
  {
    "Title": "The Other Side of Heaven",
    "fulltitle": "The Other Side of Heaven (2001)",
    "movie_year": 2001,
    "Categories": "Adventure|Biography|Drama",
    "summary": "John H. Groberg, a middle class kid from Idaho Falls, crosses the Pacific to become a Mormon missionary in the remote and exotic Tongan island kingdom during the 1950's. He leaves behind a loving family and the true love of his life, Jean. Through letters and musings across the miles, John shares his humbling and sometimes hilarious adventures with \"the girl back home\", and her letters buoy up his spirits in difficult times. John must struggle to overcome language barriers, physical hardship and deep-rooted suspicion to earn the trust and love of the Tongan people he has come to serve. Throughout his adventure-filled three years on the islands, he discovers friends and wisdom in the most unlikely places. John H. Groberg's Tongan odyssey will change his life forever.",
    "ImageURL": "https://hydramovies.com/wp-content/uploads/2018/04/The-Other-Side-of-Heaven-Movie-Poster.jpg",
    "imdb_id": "tt0250371",
    "imdb_rating": 6.5,
    "runtime": 113,
    "language": "English",
    "ytid": "5dKsHYzIoUI"
  },
  {
    "Title": "Sons of Ben",
    "fulltitle": "Sons of Ben (2016)",
    "movie_year": 2016,
    "Categories": "Biography|Documentary|Sport",
    "summary": "After many rumors of an MLS team arriving in Philadelphia never materializing, a small group of soccer fans took matters into their own hands and started a supporters group called the Sons of Ben to help bring a team to their hometown. They were a group without a team to root for and had a modest goal of reaching 100 members by the end of the year. Little did they know they would reach over 1,500 members in less time than that and start a movement that would not only change the soccer landscape in Philadelphia forever, but also help revive a community that had been struggling for decades.",
    "ImageURL": "https://hydramovies.com/wp-content/uploads/2018/04/Sons-of-Ben-Movie-Poster.jpg",
    "imdb_id": "tt2317088",
    "imdb_rating": 7.8,
    "runtime": 75,
    "language": "English",
    "ytid": "m8I_pgCaRsM"
  },
  {
    "Title": "12 Strong",
    "fulltitle": "12 Strong (2018)",
    "movie_year": 2018,
    "Categories": "Action|Drama|History|War",
    "summary": "The True Story of the Army's Special Forces \"Green Berets\", who within weeks responded to the 9-11 attack. Green Berets, with the help of the 160th SOAR(A), took over the country and allowed other Special Forces and the rest of the conventional military to begin the more publicly visible war.",
    "ImageURL": "https://hydramovies.com/wp-content/uploads/2018/04/12-Strong-Movie-Poster.jpg",
    "imdb_id": "tt1413492",
    "imdb_rating": 6.7,
    "runtime": 130,
    "language": "English",
    "ytid": "-Denciie5oA"
  },
  {
    "Title": "The Commuter",
    "fulltitle": "The Commuter (2018)",
    "movie_year": 2018,
    "Categories": "Action|Crime|Drama|Mystery|Thriller",
    "summary": "Now a hard-working life insurance salesman and a caring family man, the former police officer, Michael MacCauley, has taken the commuter rail to New York for the past ten years. But, unexpectedly, things will take a turn for the worse, when on one of his daily journeys, the cryptic passenger, Joanna, makes Michael a generous and tempting offer to locate a single commuter or face grave consequences. Is this a sick joke, or is this indeed a serious situation? As Michael races against the clock to solve this wicked conundrum, everyone aboard is a suspect, in a deal where there's definitely more than meets the eye. Can he decide in time who's the one?",
    "ImageURL": "https://hydramovies.com/wp-content/uploads/2018/04/The-Commuter-Movie-Poster.jpg",
    "imdb_id": "tt1590193",
    "imdb_rating": 6.3,
    "runtime": 105,
    "language": "English",
    "ytid": "WWexI9YiLSc"
  },
  {
    "Title": "Birdshot",
    "fulltitle": "Birdshot (2016)",
    "movie_year": 2016,
    "Categories": "Drama|Mystery|Thriller",
    "summary": "Birdshot\" is a mystery-thriller film that tells a story of a young Filipina farm girl who wanders into the boundaries of a Philippine reservation forest. Deep within the reservation she mistakenly shoots and kills a critically endangered and protected Philippine Eagle. As the local authorities begin a manhunt to track down the poacher of a national bird, their investigation leads them to an even more horrific discovery.",
    "ImageURL": "https://hydramovies.com/wp-content/uploads/2018/04/Birdshot-Movie-Poster.jpg",
    "imdb_id": "tt6135042",
    "imdb_rating": 6.8,
    "runtime": 116,
    "language": "English",
    "ytid": "7k8h_X3GjgM"
  },
  {
    "Title": "May",
    "fulltitle": "May (2002)",
    "movie_year": 2002,
    "Categories": "Drama|Horror",
    "summary": "When May was a child, she was a lonely girl with a lazy eye and without any friends except a weird and ugly doll kept in a glass case given by her bizarre mother on her birthday. May becomes a lonely, weird young woman, working in an animal hospital and assisting the veterinarian in surgeries and sewing operated animals most of the time. Her lesbian colleague Polly has a sort of attraction for her. When the shy May meets the mechanic Adam Stubbs, she loves his hands and has a crush on him. They date, but the weirdness and bizarre behavior of May pushes Adam away from her. Alone, May has a brief affair with Polly, but she feels rejected again when her colleague meets Ambrosia. When her doll is accidentally broken, the deranged May decides to build a friend for her, using the best parts her acquaintances can offer.",
    "ImageURL": "https://hydramovies.com/wp-content/uploads/2018/04/May-Movie-Poster.jpg",
    "imdb_id": "tt0303361",
    "imdb_rating": 6.7,
    "runtime": 93,
    "language": "English",
    "ytid": "YbN_uoGQysc"
  },
  {
    "Title": "The China Hustle",
    "fulltitle": "The China Hustle (2017)",
    "movie_year": 2017,
    "Categories": "Documentary",
    "summary": "An unsettling and eye-opening Wall Street horror story about Chinese companies, the American stock market, and the opportunistic greed behind the biggest heist you've never heard of.",
    "ImageURL": "https://hydramovies.com/wp-content/uploads/2018/04/The-China-Hustle-Movie-Poster.jpg",
    "imdb_id": "tt7215388",
    "imdb_rating": 6.8,
    "runtime": 82,
    "language": "English",
    "ytid": "55892jT06aI"
  },
  {
    "Title": "The Lost Brother",
    "fulltitle": "The Lost Brother (2017)",
    "movie_year": 2017,
    "Categories": "Crime|Drama|Thriller",
    "summary": "Cetarti, a public employee who has just been fired, travels from Buenos Aires to Lapachito, a lonely town in the Chaco province. He must take care of the corpses of his mother and brother who have been brutally murdered, and with whom no bond of affection binds him. The only thing that mobilizes Cetarti to undertake the trip is the possibility of charging a modest life insurance to be able to settle in Brazil. There he meets Duarte, a sort of town capo and friend of his mother's murderer, with whom he establishes a strange society to manage and collect that money.",
    "ImageURL": "https://hydramovies.com/wp-content/uploads/2018/04/The-Lost-Brother-Movie-Poster.jpg",
    "imdb_id": "tt6522634",
    "imdb_rating": 6.7,
    "runtime": 112,
    "language": "English",
    "ytid": "1DNXCdWZuHs"
  },
  {
    "Title": "The Redeemed and the Dominant: Fittest on Earth",
    "fulltitle": "The Redeemed and the Dominant: Fittest on Earth (2018)",
    "movie_year": 2018,
    "Categories": "Documentary",
    "summary": "In 2017 the fittest athletes on Earth took on the unknown and unknowable during four of the most intense days of competition in CrossFit Games history. \"The Redeemed and the Dominant: Fittest on Earth \" captures all the drama as top athletes resembling chiseled Grecian gods descend on Madison, Wisconsin, to face a series of trials. Hercules faced 12; they take on 13. Emotions run high as a throng of Australian athletes rise to the top. By the end of the competition, some learn tough lessons-that all that glitters isn't gold, or even bronze-and some learn that they're even stronger than they realized. The best among them enter the pantheon of CrossFit giants and earn the right to call themselves the \"Fittest on Earth.",
    "ImageURL": "https://hydramovies.com/wp-content/uploads/2018/04/The-Redeemed-and-the-Dominant-Fittest-on-Earth-Movie-Poster.jpg",
    "imdb_id": "tt8144778",
    "imdb_rating": 7.1,
    "runtime": 119,
    "language": "English",
    "ytid": "rlZ5MG-E2Ls"
  },
  {
    "Title": "First Match",
    "fulltitle": "First Match (2018)",
    "movie_year": 2018,
    "Categories": "Drama|Sport",
    "summary": "Hardened by years in foster care, a teenage girl from Brooklyn's Brownsville neighborhood decides that joining the boys wrestling team is the only way back to her estranged father.",
    "ImageURL": "https://hydramovies.com/wp-content/uploads/2018/04/First-Match-Movie-Poster.jpg",
    "imdb_id": "tt6061074",
    "imdb_rating": 6.1,
    "runtime": 102,
    "language": "English",
    "ytid": "Xva2FWNdcD0"
  },
  {
    "Title": "Re: Born",
    "fulltitle": "Re: Born (2016)",
    "movie_year": 2016,
    "Categories": "Action|Crime|Drama|War",
    "summary": "A legend covert soldier with a mysterious past now decides to once again unleash his beast inside of him to stand up for what he cares about.",
    "ImageURL": "https://hydramovies.com/wp-content/uploads/2018/04/Re-Born-Movie-Poster.jpg",
    "imdb_id": "tt5678110",
    "imdb_rating": 6,
    "runtime": 115,
    "language": "English",
    "ytid": "uxM6vsMNwXs"
  },
  {
    "Title": "A Moving Romance",
    "fulltitle": "A Moving Romance (2017)",
    "movie_year": 2017,
    "Categories": "Family",
    "summary": "Interior designer Olivia Wilson loses her job in New York. With newfound time on her hands she decides to head home to California to surprise her dad, Neil for the 25th anniversary of the family business, Wilson Family Movers. Upon arrival she meets the newest member of the Wilson team, Scott. With business coming to a halt, she and Scott work together to get things back on track. Just as the two begin to form a bond, Olivia is faced with a difficult decision when a worthwhile job opportunity pops up back in New York.",
    "ImageURL": "https://hydramovies.com/wp-content/uploads/2018/04/A-Moving-Romance-Movie-Poster.jpg",
    "imdb_id": "tt5039242",
    "imdb_rating": 6.1,
    "runtime": 90,
    "language": "English",
    "ytid": ""
  },
  {
    "Title": "Happy End",
    "fulltitle": "Happy End (2017)",
    "movie_year": 2017,
    "Categories": "Drama",
    "summary": "Gradually succumbing to dementia, George Laurent, the octogenarian patriarch of the Laurents, an affluent upper-bourgeois family, is uncomfortably sharing his palatial manor in Calais, the heart of the infamous migrant jungle, with his twice-married son, Thomas, and Anne, his workaholic daughter who has taken over the family construction business. Divorced and frigid, Anne has to handle the impact of a disastrous workplace accident caused by her disappointing son Pierre's negligence, while at the same time, the urgent hospitalisation of Thomas' ex-wife from a mysterious poisoning, leads his sulky 13-year-old daughter, Ève, to live with her father and his new wife, Anais. Undoubtedly, in this family, everyone has a skeleton in the closet, and as the fates of the Laurents enmesh with insistent and ignoble desires, a peculiar and disturbing alliance will form. But in the end, some secrets are bigger than others.",
    "ImageURL": "https://hydramovies.com/wp-content/uploads/2018/04/Happy-End-Movie-Poster.jpg",
    "imdb_id": "tt5304464",
    "imdb_rating": 6.9,
    "runtime": 107,
    "language": "English",
    "ytid": "cZ1ajZRn8YM"
  },
  {
    "Title": "After the Storm",
    "fulltitle": "After the Storm (2016)",
    "movie_year": 2016,
    "Categories": "Comedy|Drama",
    "summary": "Dwelling on his past glory as a prize-winning author, Ryota (Hiroshi Abe) wastes the money he makes as a private detective on gambling and can barely pay child support. After the death of his father, his aging mother (Kirin Kiki) and beautiful ex-wife (Yoko Make) seem to be moving on with their lives. Renewing contact with his initially distrusting family, Ryota struggles to take back control of his existence and to find a lasting place in the life of his young son (Taiyo Yoshizawa) - until a stormy summer night offers them a chance to truly bond again.",
    "ImageURL": "https://hydramovies.com/wp-content/uploads/2018/04/After-the-Storm-Movie-Poster.jpg",
    "imdb_id": "tt5294966",
    "imdb_rating": 7.4,
    "runtime": 118,
    "language": "English",
    "ytid": "i0lr6hfRG9s"
  },
  {
    "Title": "Mary and the Witch's Flower",
    "fulltitle": "Mary and the Witch's Flower (2017)",
    "movie_year": 2017,
    "Categories": "Adventure|Animation|Family|Fantasy",
    "summary": "Mary is an ordinary young girl stuck in the country with her Great-Aunt Charlotte and seemingly no adventures or friends in sight. She follows a mysterious cat into the nearby forest, where she discovers an old broomstick and the strange Fly-by-Night flower, a rare plant that blossoms only once every seven years and only in that forest. Together the flower and the broomstick whisk Mary above the clouds and far away to Endor College - a school of magic run by headmistress Madam Mumblechook and the brilliant Doctor Dee. But there are terrible things happening at the school, and, when Mary tells a lie, she must risk her life to try to set things right. Based on Mary Stewart's 1971 classic children's book \"The Little Broomstick\", \"Mary and The Witch's Flower\" is an action-packed film full of jaw-dropping imaginative worlds, ingenious characters, and the stirring, heartfelt story of a young girl trying to find a place in the world. Featuring the voices of Ruby Barnhill and Academy ...",
    "ImageURL": "https://hydramovies.com/wp-content/uploads/2018/04/Mary-and-the-Witchs-Flower-Movie-Poster.jpg",
    "imdb_id": "tt6336356",
    "imdb_rating": 6.8,
    "runtime": 102,
    "language": "English",
    "ytid": "888z3ku4t3I"
  },
  {
    "Title": "The Last Movie Star",
    "fulltitle": "The Last Movie Star (2017)",
    "movie_year": 2017,
    "Categories": "Drama",
    "summary": "An aging former movie star is forced to face the reality that his glory days are behind him. On its surface, the film is a tale about faded fame. At its core, it's a universal story about growing old.",
    "ImageURL": "https://hydramovies.com/wp-content/uploads/2018/04/The-Last-Movie-Star-Movie-Poster.jpg",
    "imdb_id": "tt5836316",
    "imdb_rating": 6.8,
    "runtime": 94,
    "language": "English",
    "ytid": "1-f8O118hnE"
  },
  {
    "Title": "Lucky",
    "fulltitle": "Lucky (2017)",
    "movie_year": 2017,
    "Categories": "Comedy|Drama",
    "summary": "Lucky is an old US Navy veteran of rigid habits and attitudes in a small town. When his routine is interrupted by a sudden collapse at home, Lucky finds himself realizing that his remarkably healthy old age is going to face an inevitable decline and he has to accept it. In that difficult reassessment, Lucky must face up to what he believes in and how much it compares to his neighbors' priorities. In doing so, Lucky finds that his life has its positive side as he searches for some meaning that he can accept.",
    "ImageURL": "https://hydramovies.com/wp-content/uploads/2018/04/Lucky-Movie-Poster.jpg",
    "imdb_id": "tt5859238",
    "imdb_rating": 7.4,
    "runtime": 88,
    "language": "English",
    "ytid": "2KLLkj84GAo"
  },
  {
    "Title": "Phantom Thread",
    "fulltitle": "Phantom Thread (2017)",
    "movie_year": 2017,
    "Categories": "Drama|Romance",
    "summary": "Set in the glamour of 1950s post-war London, renowned dressmaker Reynolds Woodcock (Daniel Day-Lewis) and his sister Cyril (Lesley Manville) are at the center of British fashion, dressing royalty, movie stars, heiresses, socialites, debutants, and dames with the distinct style of The House of Woodcock. Women come and go through Woodcock's life, providing the confirmed bachelor with inspiration and companionship, until he comes across a young, strong-willed woman, Alma (Vicky Krieps), who soon becomes a fixture in his life as his muse and lover. Once controlled and planned, he finds his carefully tailored life disrupted by love.",
    "ImageURL": "https://hydramovies.com/wp-content/uploads/2018/04/Phantom-Thread-Movie-Poster.jpg",
    "imdb_id": "tt5776858",
    "imdb_rating": 7.7,
    "runtime": 130,
    "language": "English",
    "ytid": "asbg5u5j0YI"
  },
  {
    "Title": "Molly's Game",
    "fulltitle": "Molly's Game (2017)",
    "movie_year": 2017,
    "Categories": "Biography|Crime|Drama",
    "summary": "Molly Bloom, a beautiful young Olympic-class skier, ran the world's most exclusive high-stakes poker game for a decade before being arrested in the middle of the night by 17 FBI agents wielding automatic weapons. Her players included Hollywood royalty, sports stars, business titans, and finally, unbeknownst to her, the Russian mob. Her only ally was her criminal defense lawyer Charlie Jaffey, who learned that there was much more to Molly than the tabloids led us to believe.",
    "ImageURL": "https://hydramovies.com/wp-content/uploads/2018/04/Mollys-Game-Movie-Poster.jpg",
    "imdb_id": "tt4209788",
    "imdb_rating": 7.5,
    "runtime": 140,
    "language": "English",
    "ytid": "Vu4UPet8Nyc"
  },
  {
    "Title": "The Third Murder",
    "fulltitle": "The Third Murder (2017)",
    "movie_year": 2017,
    "Categories": "Drama|Mystery",
    "summary": "Misumi has a criminal record dating back many years and is now under the spotlight again. It looks like an open and shut case, for Misumi has confessed to the new charge. Enter prominent lawyer Shigemori, who harbours other ideas, which could mean the difference between life and death.",
    "ImageURL": "https://hydramovies.com/wp-content/uploads/2018/04/The-Third-Murder-Movie-Poster.jpg",
    "imdb_id": "tt6410564",
    "imdb_rating": 6.8,
    "runtime": 124,
    "language": "English",
    "ytid": "Plr3V4TYBQE"
  },
  {
    "Title": "The Coming Days",
    "fulltitle": "The Coming Days (2010)",
    "movie_year": 2010,
    "Categories": "Drama|Sci-Fi",
    "summary": "In the near future the dreams of three adult siblings living in Germany are fractured by difficult romantic relationships and the unwitting involvement with an underground organization through a growing worldwide panic over the few remaining oil fields in Asia.",
    "ImageURL": "https://hydramovies.com/wp-content/uploads/2018/04/The-Coming-Days-Movie-Poster.jpg",
    "imdb_id": "tt1545985",
    "imdb_rating": 6.3,
    "runtime": 125,
    "language": "English",
    "ytid": ""
  },
  {
    "Title": "Ichi the Killer",
    "fulltitle": "Ichi the Killer (2001)",
    "movie_year": 2001,
    "Categories": "Action|Comedy|Crime|Drama|Horror",
    "summary": "When a Yakuza boss named Anjo disappears with 300 million yen, his chief henchman, a sadomasochistic man named Kakihara, and the rest of his mob goons go looking for him. After capturing and torturing a rival Yakuza member looking for answers, they soon realize they have the wrong man and begin looking for the man named Jijii who tipped them off in the first place. Soon enough Kakihara and his men encounter Ichi, a psychotic, sexually-repressed young man with amazing martial arts abilities and blades that come out of his shoes. One by one Ichi takes out members of the Yakuza and all the while Kakihara intensifies his pursuit of Ichi and Ichi's controller Jijii. What will happen as the final showdown happens between the tortured and ultra-violent Ichi and the pain-craving Kakihara?",
    "ImageURL": "https://hydramovies.com/wp-content/uploads/2018/04/Ichi-the-Killer-Movie-Poster.jpg",
    "imdb_id": "tt0296042",
    "imdb_rating": 7.1,
    "runtime": 129,
    "language": "English",
    "ytid": "iFUMtrAMknE"
  },
  {
    "Title": "The Boy with the Topknot",
    "fulltitle": "The Boy with the Topknot (2017)",
    "movie_year": 2017,
    "Categories": "Drama",
    "summary": "One-off drama based on the critically acclaimed memoirs of British journalist Sathnam Sanghera. A touching, humorous and emotional rites-of-passage story.",
    "ImageURL": "https://hydramovies.com/wp-content/uploads/2018/04/The-Boy-with-the-Topknot-Movie-Poster.jpg",
    "imdb_id": "tt5757738",
    "imdb_rating": 6.7,
    "runtime": 90,
    "language": "English",
    "ytid": "RLEnTBG7ncQ"
  }]